### PR TITLE
Buyt 26 profile

### PR DESCRIPTION
**Pull request by mishaakamichael999**

### CODE REVIEW

**Review by VKuzmich — COMMENTED** [review]
All checks have failed. Have you ever tried to solve it?

**Comment by mishaakamichael999** [comment]
> All checks have failed. Have you ever tried to solve it?



> All checks have failed. Have you ever tried to solve it?

Test was solved as well as bug on google profile picture
Ready to merge

**Comment by mishaakamichael999** [comment]
> All checks have failed. Have you ever tried to solve it?

Test was solved as well as bug on google profile picture
Ready to merge

**Review by KirilllP — APPROVED** [review]
nice flag

**Review by maks2708 — APPROVED** [review]

**Pull request merged**
